USE ROLE ACCOUNTADMIN;
USE WAREHOUSE ADMIN_WH;
USE DATABASE DEMO_DB;
USE SCHEMA SHAKE_SHACK;

-- ============================================================
-- SHAKE SHACK MARKETING INTELLIGENCE AGENT - TABLE DEFINITIONS
-- ============================================================

-- 1. LOCATIONS (275 rows)
CREATE OR REPLACE TABLE DEMO_DB.SHAKE_SHACK.MKT_LOCATIONS (
    LOCATION_ID         VARCHAR(20)     NOT NULL PRIMARY KEY,
    LOCATION_NAME       VARCHAR(100)    NOT NULL,
    MARKET              VARCHAR(50)     NOT NULL,
    REGION              VARCHAR(30)     NOT NULL,
    COUNTRY             VARCHAR(30)     NOT NULL DEFAULT 'US',
    STATE               VARCHAR(5),
    CITY                VARCHAR(100),
    LAT                 NUMBER(12,8),
    LON                 NUMBER(12,8),
    FORMAT              VARCHAR(30)     NOT NULL,
    OPEN_DATE           DATE            NOT NULL,
    IS_NEW_MARKET       BOOLEAN         NOT NULL DEFAULT FALSE,
    CHANNELS_AVAILABLE  VARCHAR(200),
    ANNUAL_REVENUE      NUMBER(12,0),
    AVG_WEEKLY_TRANSACTIONS NUMBER(10,0),
    TRADE_AREA_POPULATION   NUMBER(12,0),
    MEDIAN_HH_INCOME    NUMBER(12,0)
);

-- 2. MENU_ITEMS (175 rows)
CREATE OR REPLACE TABLE DEMO_DB.SHAKE_SHACK.MKT_MENU_ITEMS (
    MENU_ITEM_ID        VARCHAR(20)     NOT NULL PRIMARY KEY,
    ITEM_NAME           VARCHAR(100)    NOT NULL,
    CATEGORY            VARCHAR(30)     NOT NULL,
    SUBCATEGORY         VARCHAR(50),
    REGION              VARCHAR(30)     NOT NULL DEFAULT 'GLOBAL',
    BASE_PRICE          NUMBER(10,2)    NOT NULL,
    FOOD_COST           NUMBER(10,2),
    FOOD_COST_PCT       NUMBER(5,2),
    IS_LTO              BOOLEAN         NOT NULL DEFAULT FALSE,
    IS_CORE_MENU        BOOLEAN         NOT NULL DEFAULT TRUE,
    PROTEIN_TYPE        VARCHAR(20),
    LAUNCH_DATE         DATE,
    END_DATE            DATE,
    STAGE_GATE_STATUS   VARCHAR(20),
    PROMOTED_TO_CORE    BOOLEAN         NOT NULL DEFAULT FALSE,
    CALORIE_COUNT       NUMBER(6,0)
);

-- 3. CHANNEL_ECONOMICS (7 rows)
CREATE OR REPLACE TABLE DEMO_DB.SHAKE_SHACK.MKT_CHANNEL_ECONOMICS (
    CHANNEL                     VARCHAR(30)     NOT NULL PRIMARY KEY,
    COMMISSION_PCT              NUMBER(5,2)     NOT NULL,
    DELIVERY_COST_AVG           NUMBER(10,2),
    PACKAGING_COST_AVG          NUMBER(10,2),
    TECHNOLOGY_COST_PER_ORDER   NUMBER(10,2),
    NET_MARGIN_PCT              NUMBER(5,2)     NOT NULL,
    CUSTOMER_ACQUISITION_COST   NUMBER(10,2),
    AVG_ORDER_VALUE             NUMBER(10,2)
);

-- 4. COMMODITY_PRICES (~3,300 rows)
CREATE OR REPLACE TABLE DEMO_DB.SHAKE_SHACK.MKT_COMMODITY_PRICES (
    PRICE_DATE      DATE        NOT NULL,
    COMMODITY       VARCHAR(30) NOT NULL,
    PRICE_INDEX     NUMBER(10,2) NOT NULL,
    YOY_CHANGE_PCT  NUMBER(5,2),
    MOM_CHANGE_PCT  NUMBER(5,2),
    PRIMARY KEY (PRICE_DATE, COMMODITY)
);

-- 5. WEATHER_DAILY (~150K rows)
CREATE OR REPLACE TABLE DEMO_DB.SHAKE_SHACK.MKT_WEATHER_DAILY (
    LOCATION_ID         VARCHAR(20)     NOT NULL,
    WEATHER_DATE        DATE            NOT NULL,
    HIGH_TEMP_F         NUMBER(5,1),
    LOW_TEMP_F          NUMBER(5,1),
    PRECIPITATION_IN    NUMBER(5,2),
    WEATHER_CONDITION   VARCHAR(30),
    HUMIDITY_PCT        NUMBER(5,1),
    FEELS_LIKE_F        NUMBER(5,1),
    PRIMARY KEY (LOCATION_ID, WEATHER_DATE)
);

-- 6. GUEST_PROFILES (50,000 rows)
CREATE OR REPLACE TABLE DEMO_DB.SHAKE_SHACK.MKT_GUEST_PROFILES (
    GUEST_ID                VARCHAR(36)     NOT NULL PRIMARY KEY,
    FIRST_NAME              VARCHAR(50),
    EMAIL_HASH              VARCHAR(64),
    ACQUISITION_CHANNEL     VARCHAR(30),
    ACQUISITION_DATE        DATE,
    ACQUISITION_LOCATION_ID VARCHAR(20),
    TOTAL_VISITS            NUMBER(10,0),
    AVG_ORDER_VALUE         NUMBER(10,2),
    LIFETIME_VALUE          NUMBER(12,2),
    DAYS_SINCE_LAST_VISIT   NUMBER(10,0),
    LAST_VISIT_DATE         DATE,
    FAVORITE_CATEGORY       VARCHAR(30),
    DIETARY_PREFERENCE      VARCHAR(30),
    PREFERRED_CHANNEL       VARCHAR(30),
    PREFERRED_DAYPART       VARCHAR(20),
    APP_USAGE_SCORE         NUMBER(5,2),
    PUSH_OPT_IN             BOOLEAN         DEFAULT FALSE,
    EMAIL_OPT_IN            BOOLEAN         DEFAULT TRUE,
    PROMO_RESPONSE_RATE     NUMBER(5,2),
    NPS_SCORE               NUMBER(5,0),
    RECENCY_SCORE           NUMBER(1,0),
    FREQUENCY_SCORE         NUMBER(1,0),
    MONETARY_SCORE          NUMBER(1,0),
    RFM_SEGMENT             VARCHAR(50),
    CLV_TIER                VARCHAR(20),
    BEHAVIORAL_SEGMENT      VARCHAR(50),
    CHURN_RISK_SCORE        NUMBER(5,2),
    PREDICTED_CLV           NUMBER(12,2),
    LOYALTY_PROPENSITY_SCORE NUMBER(5,2),
    LOYALTY_ENROLLED        BOOLEAN         DEFAULT FALSE,
    LOYALTY_TIER            VARCHAR(20),
    LOYALTY_POINTS_BALANCE  NUMBER(10,0)    DEFAULT 0,
    AGE_GROUP               VARCHAR(10),
    HOME_MARKET             VARCHAR(50),
    HOME_LOCATION_ID        VARCHAR(20),
    SIGNUP_COHORT           VARCHAR(10),
    CREATED_AT              TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP()
);

-- 7. LTO_CAMPAIGNS (40 rows)
CREATE OR REPLACE TABLE DEMO_DB.SHAKE_SHACK.MKT_LTO_CAMPAIGNS (
    LTO_ID                      VARCHAR(20)     NOT NULL PRIMARY KEY,
    MENU_ITEM_ID                VARCHAR(20)     NOT NULL,
    CAMPAIGN_NAME               VARCHAR(200)    NOT NULL,
    LAUNCH_DATE                 DATE            NOT NULL,
    END_DATE                    DATE,
    LAUNCH_REGION               VARCHAR(30),
    MARKETS_LAUNCHED            NUMBER(5,0),
    BASELINE_DAILY_TRAFFIC      NUMBER(10,0),
    PEAK_DAILY_TRAFFIC          NUMBER(10,0),
    INCREMENTAL_TRAFFIC_PCT     NUMBER(5,2),
    TOTAL_UNITS_SOLD            NUMBER(12,0),
    ATTACH_RATE                 NUMBER(5,2),
    NEW_GUEST_ACQUISITION       NUMBER(10,0),
    REPEAT_PURCHASE_RATE        NUMBER(5,2),
    GUEST_PROFILE_OVERLAP_PCT   NUMBER(5,2),
    SOCIAL_SENTIMENT_SCORE      NUMBER(5,2),
    FOOD_COST_PCT               NUMBER(5,2),
    PROMO_SPEND                 NUMBER(10,2),
    INCREMENTALITY_SCORE        NUMBER(5,2),
    OUTCOME                     VARCHAR(30),
    CANNIBALIZATION_PCT         NUMBER(5,2)
);

-- 8. MARKETING_CAMPAIGNS (100 rows)
CREATE OR REPLACE TABLE DEMO_DB.SHAKE_SHACK.MKT_MARKETING_CAMPAIGNS (
    CAMPAIGN_ID             VARCHAR(20)     NOT NULL PRIMARY KEY,
    CAMPAIGN_NAME           VARCHAR(200)    NOT NULL,
    CAMPAIGN_TYPE           VARCHAR(30)     NOT NULL,
    CHANNEL                 VARCHAR(30)     NOT NULL,
    TARGET_SEGMENT          VARCHAR(50),
    START_DATE              DATE            NOT NULL,
    END_DATE                DATE,
    BUDGET                  NUMBER(10,2),
    IMPRESSIONS             NUMBER(12,0),
    CLICKS                  NUMBER(10,0),
    REDEMPTIONS             NUMBER(10,0),
    INCREMENTAL_VISITS      NUMBER(10,0),
    INCREMENTAL_REVENUE     NUMBER(12,2),
    CAMPAIGN_ROI            NUMBER(5,2)
);

-- 9. TRANSACTIONS (2M+ rows)
CREATE OR REPLACE TABLE DEMO_DB.SHAKE_SHACK.MKT_TRANSACTIONS (
    TRANSACTION_ID      VARCHAR(36)     NOT NULL PRIMARY KEY,
    GUEST_ID            VARCHAR(36)     NOT NULL,
    LOCATION_ID         VARCHAR(20)     NOT NULL,
    TRANSACTION_DATE    DATE            NOT NULL,
    TRANSACTION_TIME    TIME,
    ORDER_CHANNEL       VARCHAR(30)     NOT NULL,
    ORDER_TOTAL         NUMBER(10,2)    NOT NULL,
    ITEM_COUNT          NUMBER(5,0),
    DISCOUNT_AMOUNT     NUMBER(10,2)    DEFAULT 0,
    PROMO_CODE          VARCHAR(30),
    DELIVERY_FEE        NUMBER(10,2)    DEFAULT 0,
    PLATFORM_COMMISSION NUMBER(10,2)    DEFAULT 0,
    NET_REVENUE         NUMBER(10,2),
    DAYPART             VARCHAR(20),
    IS_FIRST_VISIT      BOOLEAN         DEFAULT FALSE
);

-- 10. ORDER_ITEMS (6M+ rows)
CREATE OR REPLACE TABLE DEMO_DB.SHAKE_SHACK.MKT_ORDER_ITEMS (
    ORDER_ITEM_ID       VARCHAR(36)     NOT NULL PRIMARY KEY,
    TRANSACTION_ID      VARCHAR(36)     NOT NULL,
    MENU_ITEM_ID        VARCHAR(20)     NOT NULL,
    QUANTITY            NUMBER(5,0)     NOT NULL DEFAULT 1,
    UNIT_PRICE          NUMBER(10,2)    NOT NULL,
    LINE_TOTAL          NUMBER(10,2)    NOT NULL,
    IS_LTO_ITEM         BOOLEAN         DEFAULT FALSE,
    IS_UPSELL           BOOLEAN         DEFAULT FALSE
);
