USE ROLE SALES_ENGINEER;
USE WAREHOUSE SE_WH;
USE SCHEMA TEMP.EESCOBAR;

--TABLE:MKT_CHANNEL_ECONOMICS
create or replace TABLE MKT_CHANNEL_ECONOMICS (
	CHANNEL VARCHAR(30) NOT NULL,
	COMMISSION_PCT NUMBER(5,2) NOT NULL,
	DELIVERY_COST_AVG NUMBER(10,2),
	PACKAGING_COST_AVG NUMBER(10,2),
	TECHNOLOGY_COST_PER_ORDER NUMBER(10,2),
	NET_MARGIN_PCT NUMBER(5,2) NOT NULL,
	CUSTOMER_ACQUISITION_COST NUMBER(10,2),
	AVG_ORDER_VALUE NUMBER(10,2),
	primary key (CHANNEL)
);

--TABLE:MKT_CHANNEL_FINANCIAL_MART
create or replace TABLE MKT_CHANNEL_FINANCIAL_MART (
	TRANSACTION_ID VARCHAR(36),
	GUEST_ID VARCHAR(36),
	LOCATION_ID VARCHAR(20),
	TRANSACTION_DATE DATE,
	ORDER_CHANNEL VARCHAR(30),
	ORDER_TOTAL NUMBER(10,2),
	DISCOUNT_AMOUNT NUMBER(10,2),
	DELIVERY_FEE NUMBER(10,2),
	PLATFORM_COMMISSION NUMBER(10,2),
	NET_REVENUE NUMBER(10,2),
	DAYPART VARCHAR(20),
	ITEM_COUNT NUMBER(5,0),
	IS_FIRST_VISIT BOOLEAN,
	CLV_TIER VARCHAR(20),
	RFM_SEGMENT VARCHAR(50),
	BEHAVIORAL_SEGMENT VARCHAR(50),
	ACQUISITION_CHANNEL VARCHAR(30),
	PREFERRED_CHANNEL VARCHAR(30),
	HOME_MARKET VARCHAR(50),
	AGE_GROUP VARCHAR(10),
	LOYALTY_ENROLLED BOOLEAN,
	TXN_YEAR NUMBER(4,0),
	TXN_MONTH NUMBER(2,0),
	TXN_YEAR_MONTH VARCHAR(16777216),
	TXN_QUARTER NUMBER(9,0),
	LOCATION_MARKET VARCHAR(50),
	LOCATION_REGION VARCHAR(30),
	LOCATION_FORMAT VARCHAR(30),
	IS_NEW_MARKET BOOLEAN,
	CHANNEL_COMMISSION_PCT NUMBER(5,2),
	CHANNEL_NET_MARGIN_PCT NUMBER(5,2),
	CHANNEL_CAC NUMBER(10,2),
	CHANNEL_GROUP VARCHAR(20),
	TRUE_NET_REVENUE NUMBER(14,2),
	ORDER_MARGIN_PCT NUMBER(26,2)
);

--TABLE:MKT_COMMODITY_PRICES
create or replace TABLE MKT_COMMODITY_PRICES (
	PRICE_DATE DATE NOT NULL,
	COMMODITY VARCHAR(30) NOT NULL,
	PRICE_INDEX NUMBER(10,2) NOT NULL,
	YOY_CHANGE_PCT NUMBER(5,2),
	MOM_CHANGE_PCT NUMBER(5,2),
	primary key (PRICE_DATE, COMMODITY)
);

--TABLE:MKT_CUSTOMER_INTELLIGENCE_MART
create or replace TABLE MKT_CUSTOMER_INTELLIGENCE_MART (
	GUEST_ID VARCHAR(36),
	FIRST_NAME VARCHAR(50),
	ACQUISITION_CHANNEL VARCHAR(30),
	ACQUISITION_DATE DATE,
	TOTAL_VISITS NUMBER(10,0),
	AVG_ORDER_VALUE NUMBER(10,2),
	LIFETIME_VALUE NUMBER(12,2),
	DAYS_SINCE_LAST_VISIT NUMBER(10,0),
	LAST_VISIT_DATE DATE,
	FAVORITE_CATEGORY VARCHAR(30),
	DIETARY_PREFERENCE VARCHAR(30),
	PREFERRED_CHANNEL VARCHAR(30),
	PREFERRED_DAYPART VARCHAR(20),
	APP_USAGE_SCORE NUMBER(5,2),
	PUSH_OPT_IN BOOLEAN,
	EMAIL_OPT_IN BOOLEAN,
	PROMO_RESPONSE_RATE NUMBER(5,2),
	NPS_SCORE NUMBER(5,0),
	RECENCY_SCORE NUMBER(1,0),
	FREQUENCY_SCORE NUMBER(1,0),
	MONETARY_SCORE NUMBER(1,0),
	RFM_SEGMENT VARCHAR(50),
	CLV_TIER VARCHAR(20),
	BEHAVIORAL_SEGMENT VARCHAR(50),
	CHURN_RISK_SCORE NUMBER(5,2),
	PREDICTED_CLV NUMBER(12,2),
	LOYALTY_PROPENSITY_SCORE NUMBER(5,2),
	LOYALTY_ENROLLED BOOLEAN,
	LOYALTY_TIER VARCHAR(20),
	LOYALTY_POINTS_BALANCE NUMBER(10,0),
	AGE_GROUP VARCHAR(10),
	HOME_MARKET VARCHAR(50),
	SIGNUP_COHORT VARCHAR(10),
	TXN_COUNT NUMBER(18,0),
	TOTAL_REVENUE NUMBER(22,2),
	TOTAL_NET_REVENUE NUMBER(22,2),
	AVG_TXN_VALUE NUMBER(28,8),
	TOTAL_DISCOUNTS NUMBER(22,2),
	TOTAL_COMMISSIONS NUMBER(22,2),
	VISITS_LAST_30D NUMBER(13,0),
	VISITS_LAST_60D NUMBER(13,0),
	VISITS_LAST_90D NUMBER(13,0),
	VISITS_LAST_180D NUMBER(13,0),
	VISITS_LAST_365D NUMBER(13,0),
	DELIVERY_ORDER_COUNT NUMBER(13,0),
	APP_ORDER_COUNT NUMBER(13,0),
	INSTORE_ORDER_COUNT NUMBER(13,0),
	KIOSK_ORDER_COUNT NUMBER(13,0),
	WEB_ORDER_COUNT NUMBER(13,0),
	CHANNEL_DIVERSITY NUMBER(18,0),
	MOST_COMMON_CHANNEL VARCHAR(30),
	MOST_COMMON_DAYPART VARCHAR(20),
	FIRST_TRANSACTION_DATE DATE,
	LAST_TRANSACTION_DATE DATE,
	DELIVERY_PCT NUMBER(23,2),
	APP_PCT NUMBER(23,2),
	LOCATION_MARKET VARCHAR(50),
	LOCATION_REGION VARCHAR(30),
	HOME_IS_NEW_MARKET BOOLEAN,
	HOME_LOCATION_FORMAT VARCHAR(30)
);

--TABLE:MKT_GUEST_PROFILES
create or replace TABLE MKT_GUEST_PROFILES (
	GUEST_ID VARCHAR(36) NOT NULL,
	FIRST_NAME VARCHAR(50),
	EMAIL_HASH VARCHAR(64),
	ACQUISITION_CHANNEL VARCHAR(30),
	ACQUISITION_DATE DATE,
	ACQUISITION_LOCATION_ID VARCHAR(20),
	TOTAL_VISITS NUMBER(10,0),
	AVG_ORDER_VALUE NUMBER(10,2),
	LIFETIME_VALUE NUMBER(12,2),
	DAYS_SINCE_LAST_VISIT NUMBER(10,0),
	LAST_VISIT_DATE DATE,
	FAVORITE_CATEGORY VARCHAR(30),
	DIETARY_PREFERENCE VARCHAR(30),
	PREFERRED_CHANNEL VARCHAR(30),
	PREFERRED_DAYPART VARCHAR(20),
	APP_USAGE_SCORE NUMBER(5,2),
	PUSH_OPT_IN BOOLEAN DEFAULT FALSE,
	EMAIL_OPT_IN BOOLEAN DEFAULT TRUE,
	PROMO_RESPONSE_RATE NUMBER(5,2),
	NPS_SCORE NUMBER(5,0),
	RECENCY_SCORE NUMBER(1,0),
	FREQUENCY_SCORE NUMBER(1,0),
	MONETARY_SCORE NUMBER(1,0),
	RFM_SEGMENT VARCHAR(50),
	CLV_TIER VARCHAR(20),
	BEHAVIORAL_SEGMENT VARCHAR(50),
	CHURN_RISK_SCORE NUMBER(5,2),
	PREDICTED_CLV NUMBER(12,2),
	LOYALTY_PROPENSITY_SCORE NUMBER(5,2),
	LOYALTY_ENROLLED BOOLEAN DEFAULT FALSE,
	LOYALTY_TIER VARCHAR(20),
	LOYALTY_POINTS_BALANCE NUMBER(10,0) DEFAULT 0,
	AGE_GROUP VARCHAR(10),
	HOME_MARKET VARCHAR(50),
	HOME_LOCATION_ID VARCHAR(20),
	SIGNUP_COHORT VARCHAR(10),
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	primary key (GUEST_ID)
);

--TABLE:MKT_GUEST_RETENTION_COHORT
create or replace TABLE MKT_GUEST_RETENTION_COHORT (
	GUEST_ID VARCHAR(36),
	FIRST_VISIT_DATE DATE,
	FIRST_LOCATION_ID VARCHAR(20),
	FIRST_LOCATION_FORMAT VARCHAR(30),
	FIRST_REGION VARCHAR(30),
	FIRST_MARKET VARCHAR(50),
	FIRST_ORDER_TOTAL NUMBER(10,2),
	ACQUISITION_PROMO VARCHAR(30),
	FIRST_DISCOUNT NUMBER(10,2),
	SECOND_VISIT_DATE DATE,
	SECOND_ORDER_TOTAL NUMBER(10,2),
	SECOND_VISIT_PROMO VARCHAR(30),
	SECOND_DISCOUNT NUMBER(10,2),
	DAYS_TO_RETURN NUMBER(9,0),
	RETURNED_WITHIN_30 BOOLEAN,
	SECOND_VISIT_FULL_PRICE BOOLEAN,
	DID_RETURN BOOLEAN,
	CLV_TIER VARCHAR(20),
	RFM_SEGMENT VARCHAR(50),
	CHURN_RISK_SCORE NUMBER(5,2),
	LOYALTY_ENROLLED BOOLEAN
);

--TABLE:MKT_GUEST_REVIEWS
create or replace TABLE MKT_GUEST_REVIEWS (
	REVIEW_ID VARCHAR(36) NOT NULL,
	LOCATION_ID VARCHAR(20) NOT NULL,
	PLATFORM VARCHAR(30) NOT NULL,
	REVIEW_DATE DATE NOT NULL,
	RATING NUMBER(2,1),
	REVIEW_TEXT VARCHAR(4000) NOT NULL,
	MENU_ITEMS_MENTIONED VARCHAR(500),
	LTO_ITEM_REFERENCED VARCHAR(100),
	SENTIMENT_LABEL VARCHAR(20) NOT NULL,
	SENTIMENT_SCORE NUMBER(5,2) NOT NULL,
	TOPICS VARCHAR(200) NOT NULL,
	LOCATION_MARKET VARCHAR(50) NOT NULL,
	IS_LTO_REVIEW BOOLEAN NOT NULL DEFAULT FALSE,
	primary key (REVIEW_ID)
);

--TABLE:MKT_LOCATIONS
create or replace TABLE MKT_LOCATIONS (
	LOCATION_ID VARCHAR(20) NOT NULL,
	LOCATION_NAME VARCHAR(100) NOT NULL,
	MARKET VARCHAR(50) NOT NULL,
	REGION VARCHAR(30) NOT NULL,
	COUNTRY VARCHAR(30) NOT NULL DEFAULT 'US',
	STATE VARCHAR(5),
	CITY VARCHAR(100),
	LAT NUMBER(12,8),
	LON NUMBER(12,8),
	FORMAT VARCHAR(30) NOT NULL,
	OPEN_DATE DATE NOT NULL,
	IS_NEW_MARKET BOOLEAN NOT NULL DEFAULT FALSE,
	CHANNELS_AVAILABLE VARCHAR(200),
	ANNUAL_REVENUE NUMBER(12,0),
	AVG_WEEKLY_TRANSACTIONS NUMBER(10,0),
	TRADE_AREA_POPULATION NUMBER(12,0),
	MEDIAN_HH_INCOME NUMBER(12,0),
	primary key (LOCATION_ID)
);

--TABLE:MKT_LTO_CAMPAIGNS
create or replace TABLE MKT_LTO_CAMPAIGNS (
	LTO_ID VARCHAR(20) NOT NULL,
	MENU_ITEM_ID VARCHAR(20) NOT NULL,
	CAMPAIGN_NAME VARCHAR(200) NOT NULL,
	LAUNCH_DATE DATE NOT NULL,
	END_DATE DATE,
	LAUNCH_REGION VARCHAR(30),
	MARKETS_LAUNCHED NUMBER(5,0),
	BASELINE_DAILY_TRAFFIC NUMBER(10,0),
	PEAK_DAILY_TRAFFIC NUMBER(10,0),
	INCREMENTAL_TRAFFIC_PCT NUMBER(5,2),
	TOTAL_UNITS_SOLD NUMBER(12,0),
	ATTACH_RATE NUMBER(5,2),
	NEW_GUEST_ACQUISITION NUMBER(10,0),
	REPEAT_PURCHASE_RATE NUMBER(5,2),
	GUEST_PROFILE_OVERLAP_PCT NUMBER(5,2),
	SOCIAL_SENTIMENT_SCORE NUMBER(5,2),
	FOOD_COST_PCT NUMBER(5,2),
	PROMO_SPEND NUMBER(10,2),
	INCREMENTALITY_SCORE NUMBER(5,2),
	OUTCOME VARCHAR(30),
	CANNIBALIZATION_PCT NUMBER(5,2),
	primary key (LTO_ID)
);

--TABLE:MKT_LTO_CHANNEL_ATTACH
create or replace TABLE MKT_LTO_CHANNEL_ATTACH (
	LTO_ITEM_NAME VARCHAR(100),
	LTO_MENU_ITEM_ID VARCHAR(20),
	MENU_CATEGORY VARCHAR(30),
	MENU_SUBCATEGORY VARCHAR(50),
	STAGE_GATE_STATUS VARCHAR(20),
	LTO_CAMPAIGN_NAME VARCHAR(200),
	ORDER_CHANNEL VARCHAR(30),
	TRANSACTION_DATE DATE,
	LOCATION_MARKET VARCHAR(50),
	LOCATION_REGION VARCHAR(30),
	LTO_TXNS NUMBER(18,0),
	LTO_UNITS NUMBER(17,0),
	LTO_REVENUE NUMBER(22,2),
	AVG_MARGIN_PCT NUMBER(38,8),
	CHANNEL_TOTAL_TXNS NUMBER(18,0),
	CHANNEL_ATTACH_RATE_PCT NUMBER(28,2)
);

--TABLE:MKT_MARKETING_CAMPAIGNS
create or replace TABLE MKT_MARKETING_CAMPAIGNS (
	CAMPAIGN_ID VARCHAR(20) NOT NULL,
	CAMPAIGN_NAME VARCHAR(200) NOT NULL,
	CAMPAIGN_TYPE VARCHAR(30) NOT NULL,
	CHANNEL VARCHAR(30) NOT NULL,
	TARGET_SEGMENT VARCHAR(50),
	START_DATE DATE NOT NULL,
	END_DATE DATE,
	BUDGET NUMBER(10,2),
	IMPRESSIONS NUMBER(12,0),
	CLICKS NUMBER(10,0),
	REDEMPTIONS NUMBER(10,0),
	INCREMENTAL_VISITS NUMBER(10,0),
	INCREMENTAL_REVENUE NUMBER(12,2),
	CAMPAIGN_ROI NUMBER(5,2),
	primary key (CAMPAIGN_ID)
);

--TABLE:MKT_MENU_ITEMS
create or replace TABLE MKT_MENU_ITEMS (
	MENU_ITEM_ID VARCHAR(20) NOT NULL,
	ITEM_NAME VARCHAR(100) NOT NULL,
	CATEGORY VARCHAR(30) NOT NULL,
	SUBCATEGORY VARCHAR(50),
	REGION VARCHAR(30) NOT NULL DEFAULT 'GLOBAL',
	BASE_PRICE NUMBER(10,2) NOT NULL,
	FOOD_COST NUMBER(10,2),
	FOOD_COST_PCT NUMBER(5,2),
	IS_LTO BOOLEAN NOT NULL DEFAULT FALSE,
	IS_CORE_MENU BOOLEAN NOT NULL DEFAULT TRUE,
	PROTEIN_TYPE VARCHAR(20),
	LAUNCH_DATE DATE,
	END_DATE DATE,
	STAGE_GATE_STATUS VARCHAR(20),
	PROMOTED_TO_CORE BOOLEAN NOT NULL DEFAULT FALSE,
	CALORIE_COUNT NUMBER(6,0),
	primary key (MENU_ITEM_ID)
);

--TABLE:MKT_MENU_PERFORMANCE_MART
create or replace TABLE MKT_MENU_PERFORMANCE_MART (
	ORDER_ITEM_ID VARCHAR(36),
	TRANSACTION_ID VARCHAR(36),
	TRANSACTION_DATE DATE,
	TXN_YEAR NUMBER(4,0),
	TXN_MONTH NUMBER(2,0),
	TXN_YEAR_MONTH VARCHAR(16777216),
	LOCATION_ID VARCHAR(20),
	ORDER_CHANNEL VARCHAR(30),
	GUEST_ID VARCHAR(36),
	MENU_ITEM_ID VARCHAR(20),
	ITEM_NAME VARCHAR(100),
	MENU_CATEGORY VARCHAR(30),
	MENU_SUBCATEGORY VARCHAR(50),
	MENU_REGION VARCHAR(30),
	BASE_PRICE NUMBER(10,2),
	FOOD_COST NUMBER(10,2),
	FOOD_COST_PCT NUMBER(5,2),
	IS_LTO BOOLEAN,
	IS_CORE_MENU BOOLEAN,
	PROTEIN_TYPE VARCHAR(20),
	STAGE_GATE_STATUS VARCHAR(20),
	PROMOTED_TO_CORE BOOLEAN,
	QUANTITY NUMBER(5,0),
	SOLD_PRICE NUMBER(10,2),
	LINE_TOTAL NUMBER(10,2),
	IS_LTO_ITEM BOOLEAN,
	IS_UPSELL BOOLEAN,
	ITEM_GROSS_PROFIT NUMBER(16,2),
	ITEM_MARGIN_PCT NUMBER(28,2),
	LTO_CAMPAIGN_NAME VARCHAR(200),
	LTO_INCREMENTAL_TRAFFIC_PCT NUMBER(5,2),
	LTO_ATTACH_RATE NUMBER(5,2),
	LTO_SOCIAL_SENTIMENT NUMBER(5,2),
	LTO_INCREMENTALITY_SCORE NUMBER(5,2),
	LTO_OUTCOME VARCHAR(30),
	LTO_CANNIBALIZATION_PCT NUMBER(5,2),
	LTO_GUEST_OVERLAP_PCT NUMBER(5,2),
	LTO_REPEAT_PURCHASE_RATE NUMBER(5,2),
	HIGH_TEMP_F NUMBER(5,1),
	LOW_TEMP_F NUMBER(5,1),
	PRECIPITATION_IN NUMBER(5,2),
	WEATHER_CONDITION VARCHAR(30),
	PROTEIN_PRICE_INDEX NUMBER(10,2),
	PROTEIN_YOY_CHANGE NUMBER(5,2),
	LOCATION_MARKET VARCHAR(50),
	LOCATION_REGION VARCHAR(30)
);

--TABLE:MKT_ORDER_ITEMS
create or replace TABLE MKT_ORDER_ITEMS (
	ORDER_ITEM_ID VARCHAR(36) NOT NULL,
	TRANSACTION_ID VARCHAR(36) NOT NULL,
	MENU_ITEM_ID VARCHAR(20) NOT NULL,
	QUANTITY NUMBER(5,0) NOT NULL DEFAULT 1,
	UNIT_PRICE NUMBER(10,2) NOT NULL,
	LINE_TOTAL NUMBER(10,2) NOT NULL,
	IS_LTO_ITEM BOOLEAN DEFAULT FALSE,
	IS_UPSELL BOOLEAN DEFAULT FALSE,
	primary key (ORDER_ITEM_ID)
);

--TABLE:MKT_TRANSACTIONS
create or replace TABLE MKT_TRANSACTIONS (
	TRANSACTION_ID VARCHAR(36) NOT NULL,
	GUEST_ID VARCHAR(36) NOT NULL,
	LOCATION_ID VARCHAR(20) NOT NULL,
	TRANSACTION_DATE DATE NOT NULL,
	TRANSACTION_TIME TIME(9),
	ORDER_CHANNEL VARCHAR(30) NOT NULL,
	ORDER_TOTAL NUMBER(10,2) NOT NULL,
	ITEM_COUNT NUMBER(5,0),
	DISCOUNT_AMOUNT NUMBER(10,2) DEFAULT 0,
	PROMO_CODE VARCHAR(30),
	DELIVERY_FEE NUMBER(10,2) DEFAULT 0,
	PLATFORM_COMMISSION NUMBER(10,2) DEFAULT 0,
	NET_REVENUE NUMBER(10,2),
	DAYPART VARCHAR(20),
	IS_FIRST_VISIT BOOLEAN DEFAULT FALSE,
	primary key (TRANSACTION_ID)
);

--TABLE:MKT_WEATHER_DAILY
create or replace TABLE MKT_WEATHER_DAILY (
	LOCATION_ID VARCHAR(20) NOT NULL,
	WEATHER_DATE DATE NOT NULL,
	HIGH_TEMP_F NUMBER(5,1),
	LOW_TEMP_F NUMBER(5,1),
	PRECIPITATION_IN NUMBER(5,2),
	WEATHER_CONDITION VARCHAR(30),
	HUMIDITY_PCT NUMBER(5,1),
	FEELS_LIKE_F NUMBER(5,1),
	primary key (LOCATION_ID, WEATHER_DATE)
);

