USE ROLE SALES_ENGINEER;
USE WAREHOUSE SE_WH;
USE SCHEMA TEMP.EESCOBAR;

--SEARCH:MKT_REVIEW_SEARCH_SERVICE
create or replace cortex search service MKT_REVIEW_SEARCH_SERVICE
	ON REVIEW_TEXT
	attributes PLATFORM,SENTIMENT_LABEL,LTO_ITEM_REFERENCED,IS_LTO_REVIEW,LOCATION_MARKET,TOPICS
	warehouse='SE_WH'
	target_lag='1 day'
	refresh_mode=INCREMENTAL
	as (
    SELECT
       REVIEW_ID, REVIEW_TEXT, PLATFORM,
       REVIEW_DATE::VARCHAR AS REVIEW_DATE,
       RATING::VARCHAR AS RATING,
       SENTIMENT_LABEL,
       SENTIMENT_SCORE::VARCHAR AS SENTIMENT_SCORE,
       LTO_ITEM_REFERENCED,
       COALESCE(IS_LTO_REVIEW, FALSE)::VARCHAR AS IS_LTO_REVIEW,
       MENU_ITEMS_MENTIONED, LOCATION_MARKET, TOPICS, LOCATION_ID
    FROM TEMP.EESCOBAR.MKT_GUEST_REVIEWS
);

